
        <!-- insertion de message si existant -->
                
<?php if(!isset($_SESSION['admin'])): ?> 
        
    <h2>Se connecter avec un compte administrateur</h2>

    <form class="generic-form" action="index.php?action=connexionAdmin" method="POST">

        <fieldset>
            <legend>Informations d'authentification</legend>

                <div class="row">
                    <label for="email">E-mail :</label>
                    <input id="email" type="text" name="email" data-required="" data-name="E-mail">
                </div>

                <div class="row">                    
                    <label for="password">Mot de passe :</label>
                    <input id="password" type="password" name="password" data-required="" data-name="Mot de passe">
                </div>

        </fieldset>
            <div class="centrelol">
                <input class="btnSubmit" name="submit" type="submit" value="Connexion" id="connexion">
                <button class="btnCancel"><a href="index.php">Annuler</a></button>
            </div>

    </form>



<?php elseif(isset($_SESSION['admin'])) : ?>           
        

<article id="homeAdmin">
    <a class="btnAdmin" href="index.php?action=addMeal">Ajouter un produit</a>
    <a class="btnAdmin" href="index.php?action=modifMeal">Modifier un produit</a>
    <a class="btnAdmin" href="index.php?action=listBooking">Afficher la liste des réservations</a>
    <a class="btnAdmin" href="index.php?action=listOrder">Afficher la liste des commandes</a>
</article>

<?php endif; ?>


<script type="module" src="views/js/connexion.js"></script>
